---
servers:
    - name        : "Cend_30m_2"
      username    : "11"
      password    : "22"
      ip          : 100.117.131.90
      port        : 8081
    - name        : "Cend_30m_2a"
      username    : "11"
      password    : "22"
      ip          : 100.117.131.90
      port        : 8082

stake_coin: "BUSD"
informative_coin: "BTC"

basic_symbols: False
exclude_charts: False
include_sysinfo: True
include_candle_info: False
verbose: True

side_panel_minimum_size: 107
num_days_daily: 5
num_closed_trades: 3
